# Generated by Django 2.0 on 2017-12-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDecimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
